### ISSUE TITLE
where is formula of Wm initialization in the paper?

### ISSUE THREAD

**Issue by BossunWang** [js05212/PyTorch-for-NPN#2]
Hi expert,
Nice work about different distribution for network architecture.
I would like to know this formula which initialize Wm:
https://github.com/js05212/PyTorch-for-NPN/blob/c8627cc24c4b99bb59d8eaff7beb75348e5e9c6f/npn.py#L31

**Comment by js05212** [comment]
Hi!

Thanks for your interest. This is one of the standard initialization for non-prob neural network. Any initialization for normal NN can actually be used here.

Hao
